- app/assets/javascripts/app.js
- app/config/AppConfig.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/ConfirmationController.scala
- app/controllers/auth/AuthController.scala
- app/navigation/Navigator.scala
- app/pages/CheckAnswersPage.scala
- app/views/ConfirmationView.scala.html
- app/views/components/confirmationPanel.scala.html
- app/views/components/link.scala.html
- app/views/components/strong.scala.html
- app/views/templates/Layout.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test-utils/fixtures/messages/ConfirmationMessages.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/ConfirmationControllerSpec.scala
- test/controllers/auth/AuthControllerSpec.scala
- test/views/ConfirmationViewSpec.scala
- test/views/ViewBehaviours.scala
**App-Config-base PR**
- https://github.com/hmrc/app-config-base/pull/8237 **(MERGE FIRST)**
> [ETFE-572] Add Confirmation Page

- app/controllers/HowMuchIsWrongController.scala
- app/forms/HowMuchIsWrongFormProvider.scala
- app/models/HowMuchIsWrong.scala
- app/navigation/Navigator.scala
- app/pages/HowMuchIsWrongPage.scala
- app/viewmodels/checkAnswers/CheckAnswersHelper.scala
- app/viewmodels/checkAnswers/HowMuchIsWrongSummary.scala
- app/views/HowMuchIsWrongView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test-utils/fixtures/messages/HowMuchIsWrongMessages.scala
- test-utils/generators/PageGenerators.scala
- test-utils/generators/UserAnswersEntryGenerators.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/controllers/HowMuchIsWrongControllerSpec.scala
- test/forms/HowMuchIsWrongFormProviderSpec.scala
- test/mocks/viewmodels/MockHowMuchIsWrongSummary.scala
- test/models/HowMuchIsWrongSpec.scala
- test/navigation/NavigatorSpec.scala
- test/pages/HowMuchIsWrongPageSpec.scala
- test/viewmodels/CheckAnswersHelperSpec.scala
- test/views/HowMuchIsWrongViewSpec.scala
JT PR:
- https://github.com/hmrc/emcs-tfe-journey-tests/pull/21
> ETFE-603 - SR03 - how-much-of-this-movement-is-wrong

- app/controllers/MoreInformationController.scala
- app/forms/AddMoreInformationFormProvider.scala
- app/forms/MoreInformationFormProvider.scala
- app/navigation/Navigator.scala
- app/viewmodels/AddMoreInformationHelper.scala
- app/viewmodels/checkAnswers/MoreInformationSummary.scala
- app/views/MoreInformationView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test-utils/fixtures/messages/ShortageInformationMessages.scala
- test/controllers/MoreInformationControllerSpec.scala
- test/forms/AddMoreInformationFormProviderSpec.scala
- test/forms/MoreInformationFormProviderSpec.scala
- test/navigation/NavigatorSpec.scala
- test/viewmodels/MoreInformationSummarySpec.scala
- test/views/MoreInformationViewSpec.scala
Perf PR:
- https://github.com/hmrc/emcs-tfe-performance-tests/pull/17
JT PR:
- tbc
> [ETFE-624] Refactor the MoreInformation page and add the ShortageInformation url & content

- app/viewmodels/checkAnswers/CheckAnswersHelper.scala
- test-utils/fixtures/messages/ExcessInformationMessages.scala
- test/viewmodels/CheckAnswersHelperSpec.scala
- test/viewmodels/MoreInformationSummarySpec.scala
**Notes**:
- #19 
- #20 
- #21 
- ☝️ need to be reviewed and merged prior to this, then this branch rebased from main.
Journey Test PR:
- tbc
> [ETFE-649] Updated the CheckAnswersHelper to show the Excess Information row

- app/controllers/AddMoreInformationController.scala
- app/controllers/MoreInformationController.scala
- app/navigation/Navigator.scala
- app/pages/unsatisfactory/AddDamageInformationPage.scala
- app/pages/unsatisfactory/AddSealsInformationPage.scala
- app/pages/unsatisfactory/DamageInformationPage.scala
- app/pages/unsatisfactory/SealsInformationPage.scala
- app/viewmodels/checkAnswers/CheckAnswersHelper.scala
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test-utils/fixtures/messages/AddDamageInformationMessages.scala
- test-utils/fixtures/messages/AddSealsInformationMessages.scala
- test-utils/fixtures/messages/DamageInformationMessages.scala
- test-utils/fixtures/messages/SealsInformationMessages.scala
- test/controllers/AddMoreInformationControllerSpec.scala
- test/controllers/MoreInformationControllerSpec.scala
- test/forms/AddMoreInformationFormProviderSpec.scala
- test/forms/MoreInformationFormProviderSpec.scala
- test/navigation/NavigatorSpec.scala
- test/viewmodels/CheckAnswersHelperSpec.scala
- test/viewmodels/MoreInformationSummarySpec.scala
- test/views/AddMoreInformationViewSpec.scala
- #21 
- #22 
- 👆 to be reviewed and merged prior to this
> [ETFE-638] Added remaining yesNo and info pages for WholeMovement

- app/connectors/emcsTfe/UserAnswersConnector.scala
- app/controllers/WrongWithMovementController.scala
- app/models/WrongWithMovement.scala
- app/navigation/Navigator.scala
- app/pages/unsatisfactory/individualItems/WrongWithItemPage.scala
- app/viewmodels/checkAnswers/WrongWithMovementSummary.scala
- app/viewmodels/govuk/CheckboxFluency.scala
- app/views/WrongWithMovementView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test-utils/fixtures/messages/ItemWrongWithMovementMessages.scala
- test/controllers/WrongWithMovementControllerSpec.scala
- test/forms/WrongWithMovementFormProviderSpec.scala
- test/navigation/NavigatorSpec.scala
- test/viewmodels/WrongWithMovementSummarySpec.scala
- test/views/WrongWithMovementViewSpec.scala
> [ETFE-700] Add WrongWithItem page, IDX based URL.

- app/models/response/emcsTfe/MovementItem.scala
- test-utils/fixtures/GetMovementResponseFixtures.scala
- test/connectors/emcsTfe/EmcsTfeHttpParserSpec.scala
- test/connectors/emcsTfe/GetMovementConnectorSpec.scala
**Important**:
- https://github.com/hmrc/emcs-tfe/pull/26 **must** be reviewed and merged before this PR.
> [ETFE-709] Add additional data to the GetMovement response for the Items

- app/controllers/BaseController.scala
- app/controllers/BaseNavigationController.scala
- app/controllers/CheckYourAnswersItemController.scala
- app/controllers/SelectItemsController.scala
- app/models/ItemModel.scala
- app/viewmodels/AddedItemsSummary.scala
- conf/application.conf
- test/controllers/AddedItemsControllerSpec.scala
- test/controllers/CheckYourAnswersItemControllerSpec.scala
- test/controllers/SelectItemsControllerSpec.scala
- test/viewmodels/AddedItemsSummarySpec.scala
- test/views/AddedItemsViewSpec.scala
Also added logic to not show items which haven't been completed if navigating to /:ern/:arc/add-to-list directly
> [ETFE-775] Remove added items from the SelectItem page when an item is complete

- app/controllers/BaseNavigationController.scala
- app/controllers/ItemShortageOrExcessController.scala
- app/controllers/OtherInformationController.scala
- app/forms/BaseFormProvider.scala
- app/forms/ItemShortageOrExcessFormProvider.scala
- app/forms/MoreInformationFormProvider.scala
- app/forms/OtherInformationFormProvider.scala
- app/forms/mappings/Constraints.scala
- app/utils/TimeMachine.scala
- app/views/RefusingAnyAmountOfItemView.scala.html
- test/controllers/DateOfArrivalControllerSpec.scala
- test/controllers/ItemShortageOrExcessControllerSpec.scala
- test/controllers/OtherInformationControllerSpec.scala
- test/controllers/RefusedAmountControllerSpec.scala
- test/forms/DateOfArrivalFormProviderSpec.scala
- test/forms/ItemShortageOrExcessFormProviderSpec.scala
- test/forms/MoreInformationFormProviderSpec.scala
- test/forms/OtherInformationFormProviderSpec.scala
- test/forms/mappings/ConstraintsSpec.scala
- test/views/OtherInformationViewSpec.scala
- [ETFE-822] allow MoreInformation pages through if they only have whitespace
- [ETFE-822] trim whitespace off OtherInformationController form data
> [ETFE-822] fixed issue where whitespace wouldn't be properly trimmed on bad form submissions

- app/controllers/CheckYourAnswersController.scala
- app/controllers/SelectItemsController.scala
- app/models/UserAnswers.scala
- app/models/requests/DataRequest.scala
- app/pages/unsatisfactory/individualItems/AddItemDamageInformationPage.scala
- app/pages/unsatisfactory/individualItems/AddItemSealsInformationPage.scala
- app/pages/unsatisfactory/individualItems/CheckAnswersItemPage.scala
- app/pages/unsatisfactory/individualItems/ItemDamageInformationPage.scala
- app/pages/unsatisfactory/individualItems/ItemOtherInformationPage.scala
- app/pages/unsatisfactory/individualItems/ItemSealsInformationPage.scala
- app/pages/unsatisfactory/individualItems/ItemShortageOrExcessPage.scala
- app/pages/unsatisfactory/individualItems/RefusedAmountPage.scala
- app/pages/unsatisfactory/individualItems/RefusingAnyAmountOfItemPage.scala
- app/pages/unsatisfactory/individualItems/RemoveItemPage.scala
- app/pages/unsatisfactory/individualItems/SelectItemsPage.scala
- app/pages/unsatisfactory/individualItems/WrongWithItemPage.scala
- app/viewmodels/AddedItemsSummary.scala
- app/viewmodels/ConfirmationContentHelper.scala
- test/controllers/RemoveItemControllerSpec.scala
- test/controllers/SelectItemsControllerSpec.scala
- test/mocks/viewmodels/MockCheckAnswersItemHelper.scala
- test/models/UserAnswersSpec.scala
- WIP
- [ETFE-856] Refactor frontend URLs to contain uniqueBodyReference
> [ETFE-856] Refactor frontend URLs to contain uniqueBodyReference

- app/connectors/emcsTfe/EmcsTfeHttpParser.scala
- app/connectors/emcsTfe/SubmitReportOfReceiptConnector.scala
- app/models/response/emcsTfe/SubmitReportOfReceiptResponse.scala
- test-utils/fixtures/SubmitReportOfReceiptFixtures.scala
- test/connectors/emcsTfe/SubmitReportOfReceiptConnectorSpec.scala
- test/models/response/emcsTfe/SubmitReportOfReceiptResponseSpec.scala
**Note:**
- #60 should be reviewed and merged first.
> [ETFE-842] Add connector to submit Report of Receipt model to BE.

- app/config/SessionKeys.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/ConfirmationController.scala
- app/models/response/ErrorResponse.scala
- app/services/SubmitReportOfReceiptService.scala
- app/services/UserAnswersService.scala
- test-utils/fixtures/SubmitReportOfReceiptFixtures.scala
- test/connectors/emcsTfe/SubmitReportOfReceiptConnectorSpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/ConfirmationControllerSpec.scala
- test/controllers/actions/MovementActionSpec.scala
- test/mocks/connectors/MockGetMovementConnector.scala
- test/mocks/connectors/MockSubmitReportOfReceiptConnector.scala
- test/mocks/services/MockSubmitReportOfReceiptService.scala
- test/models/submitReportOfReceipt/SubmitReportOfReceiptModelSpec.scala
- test/services/SubmitReportOfReceiptServiceSpec.scala
- test/services/UserAnswersServiceSpec.scala
**Note:**
- #61 should be reviewed and merged first
**Dependent PRs**
- https://github.com/hmrc/emcs-tfe/pull/35
- https://github.com/hmrc/emcs-tfe-chris-stub/pull/20
> [ETFE-843] Submit Report of Receipt to backend

- app/config/AppConfig.scala
- app/connectors/userAllowList/UserAllowListConnector.scala
- app/connectors/userAllowList/UserAllowListHttpParser.scala
- app/models/requests/CheckUserAllowListRequest.scala
- conf/application.conf
- test/connectors/emcsTfe/EmcsTfeHttpParserSpec.scala
- test/connectors/emcsTfe/GetMovementConnectorSpec.scala
- test/connectors/emcsTfe/UserAnswersConnectorSpec.scala
- test/connectors/emcsTfe/UserAnswersHttpParsersSpec.scala
- test/connectors/userAllowList/UserAllowListConnectorSpec.scala
- test/connectors/userAllowList/UserAllowListHttpParserSpec.scala
- test/models/requests/CheckUserAllowListRequestSpec.scala
App-Config-Base PR:
- https://github.com/hmrc/app-config-base/pull/8576
> [ETFE-911] Add Model and Connector to call user-allow-list

- app/controllers/AcceptMovementController.scala
- app/controllers/BaseController.scala
- app/controllers/BaseNavigationController.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/HowMuchIsWrongController.scala
- app/controllers/RefusingAnyAmountOfItemController.scala
- app/controllers/SelectItemsController.scala
- app/controllers/WrongWithMovementController.scala
- app/models/UserAnswers.scala
- app/models/requests/DataRequest.scala
- app/models/submitReportOfReceipt/ReceiptedItemsModel.scala
- app/navigation/Navigator.scala
- app/pages/QuestionPage.scala
- app/queries/Query.scala
- app/viewmodels/AddedItemsSummary.scala
- app/viewmodels/ConfirmationContentHelper.scala
- app/viewmodels/checkAnswers/CheckAnswersItemHelper.scala
- conf/app.routes
- conf/application.conf
- test/controllers/AcceptMovementControllerSpec.scala
- test/controllers/BaseNavigationControllerSpec.scala
- test/controllers/HowMuchIsWrongControllerSpec.scala
- test/controllers/RefusingAnyAmountOfItemControllerSpec.scala
- test/controllers/SelectItemsControllerSpec.scala
- test/controllers/WrongWithMovementControllerSpec.scala
- test/models/UserAnswersSpec.scala
- test/models/submitReportOfReceipt/ReceiptedItemsModelSpec.scala
- test/navigation/NavigatorSpec.scala
- test/resources/application.conf
- test/viewmodels/CheckAnswersItemHelperSpec.scala
- [ETFE-863] added deletion logic for Unsatisfactory/Whole
- [ETFE-863] added deletion logic for individual items (in theory) - needs testing
- [ETFE-863] added testing for deletion logic
- [ETFE-863] only display completed items, only submit completed items
> [ETFE-863] implement deletion logic

- app/views/ContinueDraftView.scala.html
- conf/messages.cy
- conf/messages.en
- test-utils/fixtures/messages/ContinueDraftMessages.scala
Also, override link on error so it jumps to the `Continue` radio option.
> [ETFE-1003] Correct error message

- app/config/AppConfig.scala
- app/controllers/LanguageSwitchController.scala
- app/controllers/actions/UserAllowListAction.scala
- app/featureswitch/api/controllers/FeatureSwitchApiController.scala
- app/featureswitch/api/services/FeatureSwitchService.scala
- app/featureswitch/core/config/FeatureSwitchRegistry.scala
- app/featureswitch/core/config/FeatureSwitching.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/featureswitch/core/models/FeatureSwitch.scala
- app/featureswitch/core/models/FeatureSwitchSetting.scala
- app/featureswitch/frontend/config/FeatureSwitchProviderConfig.scala
- app/featureswitch/frontend/connectors/FeatureSwitchApiConnector.scala
- app/featureswitch/frontend/controllers/FeatureSwitchFrontendController.scala
- app/featureswitch/frontend/models/FeatureSwitchProvider.scala
- app/featureswitch/frontend/services/FeatureSwitchRetrievalService.scala
- app/featureswitch/frontend/views/feature_switch.scala.html
- app/views/JourneyRecoveryStartAgainView.scala.html
- app/views/auth/SignedOutView.scala.html
- app/views/templates/Layout.scala.html
- build.sbt
- conf/application.conf
- conf/testOnlyDoNotUseInAppConf.routes
- test/config/AppConfigSpec.scala
- test/controllers/actions/UserAllowListActionSpec.scala
App-Config-Base PR:
- https://github.com/hmrc/app-config-base/pull/8746
> [ETFE-1008] Added feature switch library and switching for legacy URLs

- README.md
- app/config/AppConfig.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/ConfirmationController.scala
- app/controllers/IndexController.scala
- app/controllers/NotPermittedPageController.scala
- app/controllers/actions/DataRequiredAction.scala
- app/pages/ConfirmationPage.scala
- app/views/NotPermittedView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test-utils/fixtures/messages/NotPermittedMessages.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/ConfirmationControllerSpec.scala
- test/controllers/NotPermittedPageControllerSpec.scala
- test/views/NotPermittedViewSpec.scala
https://jira.tools.tax.service.gov.uk/browse/ETFE-1063 is linked to https://jira.tools.tax.service.gov.uk/browse/ETFE-1116 for the page that should be shown should the user try and click the back button on the browser.
> ETFE-1063 Delete draft upon successful submission

- app/viewmodels/ItemDetailsCardHelper.scala
- app/views/ItemDetailsView.scala.html
- app/views/components/summaryCard.scala.html
- test/viewmodels/ItemDetailsCardHelperSpec.scala
**Note:**
- Raised this as a separate PR first, as it might be useful for other stories coming up. It uses the SummaryList Card implementation from the Design-System rather than our own bespoke HTML. 
- I'll then carry on and refactor & update the Final Check Answers on Monday on a separate PR
> [ETFE-1186] Initial refactor to use the GovUkFrontend built-in library helpers

- app/models/audit/AuditModel.scala
- app/models/audit/SubmitReportOfReceiptAuditModel.scala
- app/models/audit/SubmitReportOfReceiptResponseAuditModel.scala
- app/services/AuditingService.scala
- test/services/AuditServiceSpec.scala
Fixed the incorrect setting of the `tags.path` within the explicit audit by simplifying the code.
Captured output of explicit audit event 
```
{
"auditSource": "emcs-tfe-report-a-receipt-frontend",
"auditType": "SubmitReportOfReceipt",
"eventId": "e35f85b9-f2f0-4b80-a176-b8a33a26cf4c",
"tags": {
"clientIP": "-",
"X-Request-ID": "govuk-tax-9eafcf83-7c9e-45c2-8fb1-80b983345b47",
"deviceID": "mdtpdi#75084846-8bce-4075-9573-d49cc6c9947a#1679236060806_GlnirfZQ76lHwXlTP4d/+w==",
"clientPort": "-",
"path": "/emcs/report-receipt/trader/GB00001234569/movement/18GB00000000000232361/check-answers",
"X-Session-ID": "session-d74fd476-200e-44ea-940f-4783b3397192",
"Akamai-Reputation": "-"
},
"detail": {
"credentialId": "2033040743071437",
"internalId": "Int-e60659be-e0ed-4dd8-8283-bf3a30e5ec0b", …
```
> [ETFE-1533] Correct auditing `tags.path`

- app/models/audit/SubmitReportOfReceiptAuditModel.scala
- app/models/submitReportOfReceipt/TraderModel.scala
- test-utils/fixtures/TraderModelFixtures.scala
- test-utils/fixtures/audit/SubmitReportOfReceiptAuditModelFixture.scala
Dependent on:
- https://github.com/hmrc/emcs-tfe/pull/60
> [ETFE-1568] Refctor for changes to TraderModel in emcs-tfe

- app/controllers/ItemDetailsController.scala
- app/views/ItemDetailsView.scala.html
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/ItemDetailsControllerSpec.scala
- test/views/ItemDetailsViewSpec.scala
> ETFE-2006 Provide option for users to continue

- .g8/datePage/app/views/$className$View.scala.html
- app/forms/mappings/LocalDateFormatter.scala
- app/viewmodels/govuk/DateFluency.scala
- app/views/DateOfArrivalView.scala.html
- test/forms/mappings/DateMappingsSpec.scala
- test/views/DateOfArrivalViewSpec.scala
Includes fix for ETFE-2003 and ETFE-2004 too.
> [ETFE-2002] Accessibility fixes for DateInput

- app/views/ConfirmationView.scala.html
- app/views/components/wordBreak.scala.html
- project/plugins.sbt
added word break for reference
> Changed the format fpr confirmationView from table to summary list.

- app/views/CheckYourAnswersView.scala.html
- app/views/components/checkAnswersItems.scala.html
- test/views/CheckYourAnswersViewSpec.scala
> [ETFE-2274] - Changed item card heading to h3 on CYA page

- app/config/AppConfig.scala
- app/connectors/nrsBroker/NRSBrokerConnector.scala
- app/connectors/nrsBroker/NRSBrokerHttpParser.scala
- app/featureswitch/core/config/FeatureSwitching.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/models/nrs/IdentityData.scala
- app/models/nrs/NRSMetadata.scala
- app/models/nrs/NRSPayload.scala
- app/models/nrs/ReportReceiptNRSSubmission.scala
- app/models/nrs/SearchKeys.scala
- app/models/response/ErrorResponse.scala
- app/models/response/nrsBroker/NRSBrokerInsertPayloadResponse.scala
- app/models/submitReportOfReceipt/SubmitReportOfReceiptModel.scala
- app/services/SubmitReportOfReceiptService.scala
- app/services/nrs/NRSBrokerService.scala
- app/utils/SHA256Hashing.scala
- conf/application.conf
- test-utils/fixtures/BaseFixtures.scala
- test-utils/fixtures/NRSBrokerFixtures.scala
- test/connectors/nrsBroker/NRSBrokerConnectorSpec.scala
- test/connectors/nrsBroker/NRSBrokerHttpParserSpec.scala
- test/controllers/DateOfArrivalControllerSpec.scala
- test/forms/DateOfArrivalFormProviderSpec.scala
- test/mocks/config/MockAppConfig.scala
- test/mocks/connectors/MockAuthConnector.scala
- test/mocks/connectors/MockNRSBrokerConnector.scala
- test/mocks/services/MockNRSBrokerService.scala
- test/services/SubmitReportOfReceiptServiceSpec.scala
- test/services/nrs/NRSBrokerServiceSpec.scala
- https://github.com/hmrc/app-config-base/pull/10823
- https://github.com/hmrc/app-config-qa/pull/22974
- https://github.com/hmrc/app-config-production/pull/22992
> [ETFE-4408] Add NRS submission from FE

- app/viewmodels/checkAnswers/CheckAnswersItemHelper.scala
- app/viewmodels/checkAnswers/ShortageOrExcessItemSummary.scala
- conf/messages.en
- test/mocks/viewmodels/MockShortageOrExcessItemSummary.scala
- test/viewmodels/CheckAnswersItemHelperSpec.scala
- test/viewmodels/ShortageOrExcessItemSummarySpec.scala
- https://github.com/hmrc/emcs-tfe-journey-tests/pull/564
> [ETFE-2249] Make IDs unique and add hidden change link text to be unique
